---
ID: "8f44263d-9c5b-4c43-b16b-4e34d3808ba7"
Parent: "d9f48fd4-1289-459a-8e8c-a48e4310d194"
Template: "d9f48fd4-1289-459a-8e8c-a48e4310d194"
Path: /sitecore/templates/Feature/Components/Navigation/Nav Level 1/__Standard Values
SharedFields:
- ID: "1172f251-dad4-4efb-a329-0c63500e4f1e"
  Hint: __Masters
  Value: "{944466EA-6334-47B2-8A39-6C72960280C8}"
Languages:
- Language: en
  Versions:
  - Version: 1
    Fields:
    - ID: "25bed78c-4957-4165-998a-ca1b52f67497"
      Hint: __Created
      Value: 20230131T214447Z
    - ID: "52807595-0f8f-4b20-8d2a-cb71d28c6103"
      Hint: __Owner
      Value: |
        sitecore\uy.tran@arkanedigital.com
    - ID: "5dd74568-4d4b-44c1-b513-0af5f4cda34f"
      Hint: __Created by
      Value: |
        sitecore\uy.tran@arkanedigital.com
    - ID: "8cdc337e-a112-42fb-bbb4-4143751e123f"
      Hint: __Revision
      Value: "848b1f29-6d13-4478-844a-1bb1ff0bfc98"
    - ID: "badd9cf9-53e0-4d0c-bcc0-2d784c282f6a"
      Hint: __Updated by
      Value: |
        sitecore\uy.tran@arkanedigital.com
    - ID: "d9cf14b1-fa16-4ba6-9288-e8a174d4d522"
      Hint: __Updated
      Value: 20230131T215104Z
