---
ID: "2e1f6f84-6d14-4e57-b50b-1ea5d7068955"
Parent: "fc1e86cb-01d1-4df2-aa07-92f835fc69fd"
Template: "fc1e86cb-01d1-4df2-aa07-92f835fc69fd"
Path: /sitecore/templates/Project/Basic Site/Page/__Standard Values
SharedFields:
- ID: "1172f251-dad4-4efb-a329-0c63500e4f1e"
  Hint: __Masters
  Value: |
    {FC1E86CB-01D1-4DF2-AA07-92F835FC69FD}
    {C14B6289-8AC2-439C-9E5B-40DE9F820C3F}
Languages:
- Language: en
  Versions:
  - Version: 1
    Fields:
    - ID: "1a58bc66-e969-4cb4-b8e5-25ef0ca695f6"
      Hint: Title
      Value: $name
    - ID: "25bed78c-4957-4165-998a-ca1b52f67497"
      Hint: __Created
      Value: 20221028T163051Z
    - ID: "52807595-0f8f-4b20-8d2a-cb71d28c6103"
      Hint: __Owner
      Value: |
        sitecore\Anonymous
    - ID: "5dd74568-4d4b-44c1-b513-0af5f4cda34f"
      Hint: __Created by
      Value: |
        sitecore\Anonymous
    - ID: "8cdc337e-a112-42fb-bbb4-4143751e123f"
      Hint: __Revision
      Value: "cbdf3dfe-b5a3-461a-9dab-3ffbb1e56af8"
    - ID: "badd9cf9-53e0-4d0c-bcc0-2d784c282f6a"
      Hint: __Updated by
      Value: |
        sitecore\Anonymous
    - ID: "d9cf14b1-fa16-4ba6-9288-e8a174d4d522"
      Hint: __Updated
      Value: 20221028T163057Z
